<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_field_user</name>
   <tag></tag>
   <elementGuidId>3c75ad83-dea7-41b9-8723-53a5bc7cae05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autocompletemultiple-undefined-_r_a_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocompletemultiple-undefined-_r_a_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c6d7ba0-fcc1-4358-af00-139ec7b4f61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4131c7b6-719e-4e21-9e28-e0d60d2c8cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocompletemultiple-undefined</value>
      <webElementGuid>8c3a8243-90ab-435b-af0b-712457424268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>ca78efcf-99a6-4d21-aff4-bf411f57ef88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9647adbb-6591-4a9a-b8ba-6c688756c20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocompletemultiple-undefined-_r_a_&quot;)</value>
      <webElementGuid>d2e42f64-6ff2-4d88-9e1c-d5511f6e7b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocompletemultiple-undefined-_r_a_']</value>
      <webElementGuid>2ad0fbdb-82bc-41c9-a299-70959264f423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>0a97bd7e-ee9d-44d4-bddb-74f1d3e2dc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>cc7e11d3-8a3d-4ce1-9b61-f312e87989d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autocompletemultiple-undefined-_r_a_']</value>
      <webElementGuid>0999dbb4-983b-410e-ae10-be76a47e4396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
