<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_field_businessPartner</name>
   <tag></tag>
   <elementGuidId>131367dd-e1a5-4006-aac6-8ee8bf67468b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'autocompletemultiple-serverBpMappings-_r_k_') and @name = 'serverBpMappings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autocompletemultiple-serverBpMappings-_r_k_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocompletemultiple-serverBpMappings-_r_k_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9559a3a5-7058-4871-8cd8-1c33de45e533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5c57d04-b281-4c00-ae77-e2998555cba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocompletemultiple-serverBpMappings</value>
      <webElementGuid>22da3598-42ff-4cc3-b86a-44eb3ae30a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>9eb1be1b-bd09-4bc6-98fb-7a1eed863c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08ec5e9a-21c9-48ed-9c1c-41fba742f78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serverBpMappings</value>
      <webElementGuid>6b733b46-2cfb-4d7e-9fd0-74116c48613e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocompletemultiple-serverBpMappings-_r_k_&quot;)</value>
      <webElementGuid>56fd1398-2198-4a20-943b-a3b89fe8df20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocompletemultiple-serverBpMappings-_r_k_']</value>
      <webElementGuid>469e80b9-f302-439e-9f2a-c3266a67edb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[3]/div[2]/div/div/input</value>
      <webElementGuid>837bcae5-40da-4d69-96c6-cd2f7ccce1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>b70e2654-2583-4075-9564-c46d03df7588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autocompletemultiple-serverBpMappings-_r_k_' and @name = 'serverBpMappings']</value>
      <webElementGuid>6e56af29-c640-4483-aeb0-9dffd0b70813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
