<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_field_remarks</name>
   <tag></tag>
   <elementGuidId>99aad72a-9b8c-462e-8f61-efb1ae09fff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-remarks-_r_d_']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'textarea-remarks-_r_d_') and @name = 'remarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-remarks-_r_d_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a161daf7-0918-4b69-9e93-8596cbde74af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2f49c33-8c8d-4b38-94be-20107f72a751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-remarks</value>
      <webElementGuid>6c1f1bab-bfaa-4f66-9acd-8bbe2e69f791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>226de6c2-cc78-4981-91e3-ab28d9933071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none resize-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>7690eb06-76f0-4dab-a82c-b4b46a5b85ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>debf8b63-6bc5-4c26-b54b-e0e6be4dfdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-remarks-_r_d_&quot;)</value>
      <webElementGuid>935de640-7565-4cd6-a348-65bf3881902d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-remarks-_r_d_']</value>
      <webElementGuid>0c1f1b8a-ec6a-40ca-b145-92c33c592db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[5]/div[2]/div/textarea</value>
      <webElementGuid>5618b0c5-56ec-4c67-ac0e-90fb96dbc240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e31d245d-9469-4239-8da8-cb9b664b74ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-remarks-_r_d_' and @name = 'remarks']</value>
      <webElementGuid>a5589f2c-25b8-4877-9f69-691e071d6fa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
