<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_field_rule_definition</name>
   <tag></tag>
   <elementGuidId>054632c4-7fda-480e-a801-7eecf9b5775a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'textfield-ruleDefinition') and @name = 'ruleDefinition']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield-ruleDefinition-_r_e_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textfield-ruleDefinition-_r_e_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6e1b5ca-e9d8-4c15-aeed-88d02bec1909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ebcb066-0202-49a9-a34c-1a8924bf7293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield-ruleDefinition</value>
      <webElementGuid>97054200-befb-4bfe-9aa2-c8a52be047f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark text-neutral-90 dark:text-neutral-90-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>cf5e2dd6-8d7a-439e-b8cf-f48b2d04d70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruleDefinition</value>
      <webElementGuid>4aee4444-7a60-49b9-bcbe-f73e46de5af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textfield-ruleDefinition-_r_e_&quot;)</value>
      <webElementGuid>f4050fdb-0706-42c4-abaf-bb3b31a21199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield-ruleDefinition-_r_e_']</value>
      <webElementGuid>e96a7b80-905f-4b29-9926-dae96998e5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[3]/div[2]/div/input</value>
      <webElementGuid>9cf18331-3faa-43fd-b230-571ac358bcda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>746bef57-8145-48ab-9465-e59530d97bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textfield-ruleDefinition-_r_e_' and @name = 'ruleDefinition']</value>
      <webElementGuid>7cae66ed-b1dc-4d69-bfe9-7f886d7327d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
