<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_field_model_record_rule</name>
   <tag></tag>
   <elementGuidId>863d5ceb-4148-4ed8-8bcf-490e586d17fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'autocomplete-entityName') and @name = 'entityName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autocomplete-entityName-_r_d_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocomplete-entityName-_r_d_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92da22fd-3a41-4db5-92d2-71d71b65a361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>286b58a5-8778-4994-856c-592d8e00a5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete-entityName</value>
      <webElementGuid>4b9a0154-4d23-4cf5-b5f5-172c3beb4479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark text-neutral-90 dark:text-neutral-90-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>d6c8944d-7594-48d2-bc6b-9a86037c195b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc5d225b-7f10-4c5e-8455-f68939afc2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>entityName</value>
      <webElementGuid>100e25b6-e6ab-4ed0-8789-d099ed77ecfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete-entityName-_r_d_&quot;)</value>
      <webElementGuid>de5a81a6-1663-4b21-b39f-73304c3ef73a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocomplete-entityName-_r_d_']</value>
      <webElementGuid>78556e74-29d4-4d3a-b22b-2b57e6855e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[2]/div[2]/div/input</value>
      <webElementGuid>6dfac0b6-df6c-42ea-a60a-350b6201b8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>334079b6-50cf-4e2a-9573-556dec5d923d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autocomplete-entityName-_r_d_' and @name = 'entityName']</value>
      <webElementGuid>00e58236-b148-49cd-b98b-fab902b86bb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
