<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_status_record_rule</name>
   <tag></tag>
   <elementGuidId>b2b0ef9c-2bc3-4005-896f-70bf402771e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86438138-9e09-4a83-b83c-457546a2e96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>feff8049-b7ac-493d-aae0-a90a6825180b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3612b68f-0bfe-4e69-85dd-539e6a9b4f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-full transition-colors relative focus:ring-3 ring-primary-focus dark:ring-primary-focus-dark w-7 h-4 bg-neutral-40 dark:bg-neutral-40-dark</value>
      <webElementGuid>024f7fad-a9be-49b5-8751-5ea38da7b607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;relative min-h-screen min-w-screen-lg bg-neutral-15 pt-20&quot;]/div[2]/div[@class=&quot;px-6 py-4 flex flex-col gap-4&quot;]/div[@class=&quot;bg-neutral-10 rounded-2xl p-4 border border-neutral-30&quot;]/form[@class=&quot;w-full max-w-screen-sm flex flex-col gap-3&quot;]/div[@class=&quot;flex gap-3 min-h-8 items-start&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative flex text-neutral-90 dark:text-neutral-90-dark flex-col gap-0.5&quot;]/div[@class=&quot;w-fit flex items-center gap-2.5 rounded-md py-1.5&quot;]/div[1]/div[@class=&quot;rounded-full transition-colors relative focus:ring-3 ring-primary-focus dark:ring-primary-focus-dark w-7 h-4 bg-neutral-40 dark:bg-neutral-40-dark&quot;]</value>
      <webElementGuid>64b40448-2846-4e34-a29b-d8349ada2b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/div/div/div</value>
      <webElementGuid>3f43d9ec-9c3e-43c6-b250-72a9b5bed48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[10]</value>
      <webElementGuid>7d00ec8b-c6ed-45c7-9035-e57625c007d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[15]</value>
      <webElementGuid>d5e30e4a-68ba-4666-aece-e6e74148d5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[2]</value>
      <webElementGuid>0eb51c99-9a32-40da-8b3e-207ad72b73c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::div[4]</value>
      <webElementGuid>493bd4ba-cf56-4c5f-b0ae-8cf280dfc6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>3bc54a4c-d98c-4334-8916-918b26f25727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
