<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QR Code Number loginKey</name>
   <tag></tag>
   <elementGuidId>a396ba54-9296-4ac9-9bae-225b49b08ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textfield-loginKey-_r_1_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield-loginKey-_r_1_']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'textfield-loginKey') and @name = 'loginKey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae8d5a68-1b22-4c55-bf8b-5fff570557d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>879a4314-cc8b-40db-bf73-baf7e6dceca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield-loginKey</value>
      <webElementGuid>6298353a-a928-458e-aa7d-34bdb9a1eb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark text-neutral-90 dark:text-neutral-90-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>c5b28626-a261-4b3a-96d1-89cabef18b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>QR Code Number</value>
      <webElementGuid>221d10a4-b057-46c7-8105-0722b30af2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>702eb962d67d47aa9d156f6148de9848</value>
      <webElementGuid>10d3d001-f69e-4790-a808-f9189caaee06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginKey</value>
      <webElementGuid>47dd7a2e-05ed-4932-8d0b-82e20fa5cf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textfield-loginKey-_r_1_&quot;)</value>
      <webElementGuid>305c6a19-40d6-40a8-bbd0-09cff0b30744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield-loginKey-_r_1_']</value>
      <webElementGuid>73913c11-3a52-4f0d-9e76-7030b6b06c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>961714b1-3250-4f1d-b234-d908aface486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7f1a83a2-97b6-48ef-a51f-d918be4c584c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textfield-loginKey-_r_1_' and @name = 'loginKey']</value>
      <webElementGuid>4e784a8f-72b6-4a49-95ba-6327ca33e25f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
