<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__daterangepicker-effective</name>
   <tag></tag>
   <elementGuidId>2ffa0e6e-3df5-430b-a734-c8d47b394d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#daterangepicker-effective</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='daterangepicker-effective']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce7f72e4-923f-4efd-bc1a-05a46e7a151a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>daterangepicker-effective</value>
      <webElementGuid>f345ec99-5722-451c-af42-c798ad541618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea7c53e4-c504-4ceb-9a4b-acb09ab43a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bde35833-81f6-4051-bb2b-8ec1d7490702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full truncate outline-none bg-transparent disabled:cursor-not-allowed text-primary-main dark:text-primary-main-dark font-medium</value>
      <webElementGuid>cdacee5e-ff1b-424d-aab9-ba9c1033dafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>effective</value>
      <webElementGuid>390e7f3b-df10-49fa-af15-ed88937ea29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daterangepicker-effective&quot;)</value>
      <webElementGuid>37f0aec6-e2cc-477c-a0da-817320233908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='daterangepicker-effective']</value>
      <webElementGuid>7da823fd-8ea2-490e-af8a-f9a386bfeb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div[2]/div[2]/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>c76b0a4e-221c-492c-8ac3-2c14fff1eadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>c930d88a-59c0-436f-b7df-c6633c52357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'daterangepicker-effective' and @name = 'effective']</value>
      <webElementGuid>4da5cadc-47b6-400f-b99a-bb33182f7a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
