<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_field_badgeNo</name>
   <tag></tag>
   <elementGuidId>5442ac08-7753-4f51-89e3-9c2c8f3db433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textfield-badgeNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield-badgeNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a0cd0a4-1e1d-439c-a86d-f0b1e636a531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield-badgeNo</value>
      <webElementGuid>44cbb2cc-fda6-4b60-8c6b-6a1b8e785035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter badge number (e.g. 200000)</value>
      <webElementGuid>cd6ce266-1b47-4673-a279-d3ab08c9c25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full min-w-0 outline-none bg-transparent text-neutral-90 dark:text-neutral-90-dark placeholder:text-neutral-50 dark:placeholder:text-neutral-50-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>1072cf55-9f79-4efd-b906-09114bf5b77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>badgeNo</value>
      <webElementGuid>b6527c26-62d4-49d7-b09d-8116b165d7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textfield-badgeNo&quot;)</value>
      <webElementGuid>9fdc9b1a-fee2-4b3c-9062-d04106645eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield-badgeNo']</value>
      <webElementGuid>858038c2-e21b-4270-a70d-c450a08d9a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>8c263207-f58d-48b4-9f51-6411132a7f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c95acb72-8578-45a3-afec-2d575f125b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textfield-badgeNo' and @placeholder = 'Enter badge number (e.g. 200000)' and @name = 'badgeNo']</value>
      <webElementGuid>3ab4c1d2-08ab-483e-b3f9-f3e2266f31ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
