<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_name_user</name>
   <tag></tag>
   <elementGuidId>93185c92-f0d5-4379-b12d-292a43155c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[22]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cc6f02b-5668-4cdc-a83e-87cf8b63059e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83e9b985-a312-44f5-b957-ea326eb20f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-3 border-b border-neutral-30 flex items-center justify-between</value>
      <webElementGuid>bf0b55cb-f69a-4845-9e12-8e0883459189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NNEHA1</value>
      <webElementGuid>5637ceff-6794-43de-b412-f6cdc7a0cc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;border border-neutral-40 dark:border-neutral-50-dark rounded-md drop-shadow-sm bg-neutral-10 dark:bg-neutral-10-dark m-8 flex flex-col max-h-[90vh]&quot;]/div[@class=&quot;pb-4 px-6 h-full flex-1 overflow-auto&quot;]/div[@class=&quot;flex gap-4&quot;]/div[@class=&quot;w-[300px]&quot;]/button[@class=&quot;w-full px-4 py-3 border-b border-neutral-30 flex items-center justify-between&quot;]</value>
      <webElementGuid>075132fc-418a-400c-8dc1-7cf9bdcad1fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>f38c502c-c1cc-4166-8fa1-696744cc77d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div[2]/div[2]/div[2]/div/button[2]</value>
      <webElementGuid>684802a3-66fc-4600-bf78-f1fd5833a9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA'])[2]/following::button[1]</value>
      <webElementGuid>dfc628da-4d80-4109-ac2e-dcc56c4ec6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Server for Each of Chosen User'])[1]/following::button[4]</value>
      <webElementGuid>42ced271-83f2-44c7-b135-de8c8d4798ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Server Name'])[1]/preceding::button[1]</value>
      <webElementGuid>1de3f4cc-e0e9-4e36-95c8-fb14f80a3e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button[2]</value>
      <webElementGuid>3cf8d2b1-806d-4420-9f2b-29f908a799c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'NNEHA1' or . = 'NNEHA1')]</value>
      <webElementGuid>064eefac-3543-49e8-94d3-7e1455da2dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
