<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_row_7</name>
   <tag></tag>
   <elementGuidId>2568cb89-048b-4931-b200-79202eeb57f7</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Master Group Detail  Lumina/input_Direct Labor_checkbox-select_row_7-_r_1o_.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Master Group Detail  Lumina/input_Direct Labor_checkbox-select_row_7-_r_1o_.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_7-_r_1o_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_7-_r_1o_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bdc2783-ce5b-4dcf-8161-046a6482af11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row</value>
      <webElementGuid>d02954d3-d3c5-49c0-97cb-dd3997b276fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91ffaddb-a2fd-4e68-a6ba-a7e0a9c9a8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>d10a8cef-cde8-4cf1-b3ce-f4327c68739b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_7</value>
      <webElementGuid>d2c5d410-ff93-4332-a5d5-75b949c3ed5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>080cea5f-3706-4d5b-8508-af45dbbe8537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_7-_r_1o_&quot;)</value>
      <webElementGuid>ae8e86c9-9d73-47e0-9398-cd17273a28fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_7-_r_1o_']</value>
      <webElementGuid>ca182378-c7f6-47c2-aae9-9d7898f099f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_7']/label/div/input</value>
      <webElementGuid>7358c682-927d-4182-970d-2d3bf8da9985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/div/label/div/input</value>
      <webElementGuid>3295fb23-ff51-40db-95a3-d95e4e5b5b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_7-_r_1o_' and @type = 'checkbox']</value>
      <webElementGuid>dc0730ed-d9e5-4966-9fd4-733a43f525cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
