<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_End tour</name>
   <tag></tag>
   <elementGuidId>671eb9d5-fdaf-4497-a866-05aab14ee765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef9ff837-cb6c-44aa-89dd-3800b79d28e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>f7705fe4-7726-49d1-9224-49f084a0f7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>skip</value>
      <webElementGuid>4f59a59e-fce5-42f5-bf15-eccc77a9e719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>623970cb-f340-4fd8-9ace-cf00e6bfaaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>5ff3f884-8633-467f-8b6a-2755730e07f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dd3a296-2b6e-4d40-a1d1-7aa36e6cabb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative rounded-md font-medium h-fit disabled:cursor-not-allowed py-1.5 px-2 text-12px focus:ring-3 disabled:text-neutral-60 dark:disabled:text-neutral-60-dark text-primary-main  dark:text-primary-main-dark  hover:text-primary-main dark:hover:text-primary-main-dark hover:bg-primary-surface  dark:hover:bg-primary-surface-dark  active:text-primary-pressed  dark:active:text-primary-pressed-dark  focus:ring-primary-focus  dark:focus:ring-primary-focus-dark</value>
      <webElementGuid>b5bec63d-4efe-456f-83c2-1c9148698b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55f8de25-1c4c-4ce4-91bc-3a1f42ad4d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>End tour</value>
      <webElementGuid>fe311653-d631-4ad5-8337-a093d05bd21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-joyride-step-0&quot;)/div[@class=&quot;relative w-[300px] ml-2&quot;]/div[@class=&quot;relative z-[2] bg-neutral-10 rounded-xl border border-neutral-20 shadow-box-notification&quot;]/div[@class=&quot;px-4 pt-4 pb-3&quot;]/div[@class=&quot;flex justify-between items-center mt-3 pt-3 border-t border-neutral-20&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/button[@class=&quot;relative rounded-md font-medium h-fit disabled:cursor-not-allowed py-1.5 px-2 text-12px focus:ring-3 disabled:text-neutral-60 dark:disabled:text-neutral-60-dark text-primary-main  dark:text-primary-main-dark  hover:text-primary-main dark:hover:text-primary-main-dark hover:bg-primary-surface  dark:hover:bg-primary-surface-dark  active:text-primary-pressed  dark:active:text-primary-pressed-dark  focus:ring-primary-focus  dark:focus:ring-primary-focus-dark&quot;]</value>
      <webElementGuid>4748ad24-a7ae-4c41-ac43-2c01a61544c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[14]</value>
      <webElementGuid>74525cef-23b8-4bc0-bde7-56caef31422a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-joyride-step-0']/div/div/div/div[2]/div/button</value>
      <webElementGuid>2134865b-ff0e-443f-b2e2-36de7298824e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter The Group Name Here'])[1]/following::button[1]</value>
      <webElementGuid>02218643-9c47-40f4-b0b4-2a1e78ae2d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::button[1]</value>
      <webElementGuid>4a487af6-5bc4-4ee5-b789-aa302b963aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div[2]/div/button</value>
      <webElementGuid>0e037ba0-e90e-4c3a-afd5-03a53953d3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Skip' and @type = 'button' and (text() = 'End tour' or . = 'End tour')]</value>
      <webElementGuid>2db89139-b4f6-49aa-a3c5-64c514fa706e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
