<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Operator Staf da_checkbox-select_row__ad1fe2</name>
   <tag></tag>
   <elementGuidId>613b8f6f-2990-42ef-98a7-47393b33351f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_1-_r_1n_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_1-_r_1n_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d42da45-46df-480e-8ae6-03a40a0a48e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_1-_r_1n_</value>
      <webElementGuid>193fbc7e-8e93-4447-a5f9-9e6a5b5430de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b388969-ab13-40fe-b83a-158f8d7d4da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>1251199d-0115-42a2-b3e2-72b86fc8965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_1</value>
      <webElementGuid>ba481372-3c71-4ebb-b72b-8f1ca3fa7e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d6a9e8f9-0761-4755-8c13-9e3567bcb79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_1-_r_1n_&quot;)</value>
      <webElementGuid>0102eef8-1d12-4c56-8686-d09c302ff99e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_1-_r_1n_']</value>
      <webElementGuid>6c241874-8a6f-4beb-8a36-636b28f738bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_1']/label/div/input</value>
      <webElementGuid>8720a4fa-8bf5-49d3-bbbd-b92c0fe2f7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/label/div/input</value>
      <webElementGuid>70f3ad89-bfb5-4725-a3ed-3a9f3266a914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_1-_r_1n_' and @type = 'checkbox']</value>
      <webElementGuid>5e206455-4308-43f9-812b-becea745ac52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
