<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indirect labor_checkbox-select_row_7-_r_17_</name>
   <tag></tag>
   <elementGuidId>81c718dd-78d4-44d0-9dfb-5351141e48db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_7-_r_17_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_7-_r_17_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58fe981c-2e56-40d4-8514-ab18bb777d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_7-_r_17_</value>
      <webElementGuid>dc067502-bb6c-4966-9b3c-7d9aa0640dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fece018f-bc89-42e9-a664-5837d9a8c854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>09930b27-742a-40dc-8290-4492f12c3b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_7</value>
      <webElementGuid>e77f21bc-b016-4827-9fb9-3b59fe92955b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d2edfba4-e755-4640-b1a3-3d701e089287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_7-_r_17_&quot;)</value>
      <webElementGuid>85852433-a087-4de9-ae97-b03fe858e3be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_7-_r_17_']</value>
      <webElementGuid>0467539e-8d83-486f-a263-9949c3123279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_7']/label/div/input</value>
      <webElementGuid>5d03ee9a-0bdd-4122-a872-2e94bf8d6c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/div/label/div/input</value>
      <webElementGuid>f5c32f65-06ef-4a06-a95d-76975cfa66ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_7-_r_17_' and @type = 'checkbox']</value>
      <webElementGuid>58554a35-4e92-4155-957f-d671535d1b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
