<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indirect labor_checkbox-select_row_9-_r_1a_</name>
   <tag></tag>
   <elementGuidId>f9a1b236-42e8-4d93-bd84-8157243a594f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_9-_r_1a_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_9-_r_1a_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acfe8ca3-5ef7-4ab0-b0f3-14446ef41cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_9-_r_1a_</value>
      <webElementGuid>88c08ac7-43a9-4583-9368-775aae1b4916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ba8c6dcc-a12f-446b-85cf-527396dba256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>7c0c8c35-c80e-4ad4-bf58-e34623adc1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_9</value>
      <webElementGuid>ee35e5dc-77dc-463e-a73e-7cd0e51b022b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b3298922-6116-4b24-86c8-0a1e650f5b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_9-_r_1a_&quot;)</value>
      <webElementGuid>9e5a0a05-d04e-44ae-8a5d-422654296ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_9-_r_1a_']</value>
      <webElementGuid>b2f90b0e-18af-4312-a218-a891a456dac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_9']/label/div/input</value>
      <webElementGuid>f5fea362-0bfc-430b-9aa9-1e6e35065e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/div/div/label/div/input</value>
      <webElementGuid>4073d004-92e8-4cee-ad56-b295361fd842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_9-_r_1a_' and @type = 'checkbox']</value>
      <webElementGuid>1ce27d7c-75e8-4bfd-9fbb-32583daf82a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
