<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Master Plants_checkbox-undefined-_r_1p_</name>
   <tag></tag>
   <elementGuidId>fef95535-a31c-417e-84c5-2f0db883eba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-undefined-_r_1p_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-undefined-_r_1p_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c47ef651-dcff-4c4b-96c8-d428bd4ba8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-undefined-_r_1p_</value>
      <webElementGuid>a302e41a-d176-424c-a050-4ffdb39e2de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>922c5d9b-3b62-4106-8514-474d29dfb093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>5c11119f-a89a-4ba8-badb-0fb8508c490a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>53988699-8f08-469a-b1e7-3602a289e040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-undefined-_r_1p_&quot;)</value>
      <webElementGuid>47bcc8e7-2039-4043-b78c-cd3bc1fc1e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-undefined-_r_1p_']</value>
      <webElementGuid>dac5b06e-c95d-460c-ba17-8d208b8d209c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-accessRight']/div/div[2]/div/table/tbody/tr/td[3]/div/div/label/div/input</value>
      <webElementGuid>4087f378-8a70-4254-acc8-ae28a4a28cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/label/div/input</value>
      <webElementGuid>fe310ea3-4e1e-43b7-93e5-817ada0b73ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-undefined-_r_1p_' and @type = 'checkbox']</value>
      <webElementGuid>2921aac2-4f8b-4d84-a10f-a6c9154e8200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
