<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Master Business Partners_checkbox-und_e876db</name>
   <tag></tag>
   <elementGuidId>b21a8bd7-6ca7-454d-920c-a05955edafbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-undefined-_r_22_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-undefined-_r_22_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9a5e992-a7e9-4c28-876d-126c9fab8014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-undefined-_r_22_</value>
      <webElementGuid>7672a598-f1e5-4317-9b93-bdb88b6cbffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12f66427-63db-4afd-b73b-78496c4155b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>a87a50b1-f29e-415a-9a5d-dd346bdc8333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a21fc08f-2c8c-4ad2-b82b-33df3b22f35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-undefined-_r_22_&quot;)</value>
      <webElementGuid>75285c0e-206e-45ef-99b5-ed6582e9274f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-undefined-_r_22_']</value>
      <webElementGuid>abddab2a-d355-48de-a7f2-275197c1ace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-accessRight']/div/div[2]/div/table/tbody/tr[2]/td[4]/div/div/label/div/input</value>
      <webElementGuid>f61edf17-3853-40da-83c1-6688fe7ef1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div/label/div/input</value>
      <webElementGuid>650c0d0d-4ea2-4017-b963-ff47160620a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-undefined-_r_22_' and @type = 'checkbox']</value>
      <webElementGuid>beff1cef-78d8-4ce0-a7c6-ad763d48413a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
