<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Plant_checkbox-select_row_0-_r_1e_</name>
   <tag></tag>
   <elementGuidId>1221842e-293a-47b5-8749-20268d603c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_0-_r_1e_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_0-_r_1e_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>839d8c5b-edb8-49f8-b715-1bf95fba1efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_0-_r_1e_</value>
      <webElementGuid>353a374a-f2cc-47f5-a280-50cbfc645e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b6b910e-fc06-4575-b852-ecd6d8ee3eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>f67e0e13-06f0-444d-8103-a92740ab27b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_0</value>
      <webElementGuid>9a9463f6-5e30-461f-91b1-8820bce43929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f1e3dac0-a71f-4e2b-9165-16ee5e46425e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_0-_r_1e_&quot;)</value>
      <webElementGuid>24ae0c48-d350-4518-8c0e-e2502638c332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_0-_r_1e_']</value>
      <webElementGuid>6b3c8972-c60d-4571-93b0-5c701fcaf849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_0']/label/div/input</value>
      <webElementGuid>cf253c65-8ee5-43a3-83c5-41600f0e6a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/label/div/input</value>
      <webElementGuid>62c40f4a-dc52-4678-a47d-c31cc4626b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_0-_r_1e_' and @type = 'checkbox']</value>
      <webElementGuid>15eda106-ff43-4150-a6e0-efdfbabd7b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
