<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Master Plants_checkbox-undefined-_r_1q_</name>
   <tag></tag>
   <elementGuidId>59d502d9-6c54-4679-9e14-4955c5789a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-undefined-_r_1q_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-undefined-_r_1q_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32c67e3d-f3b2-4d9b-b143-f6aba3d36521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-undefined-_r_1q_</value>
      <webElementGuid>2059e787-0764-4a22-ad86-0e4b7e50d060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>97b335a7-5884-45b8-947f-591aa3ff321e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>f1008682-3fc4-4817-b23a-afc40c1ef225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1e05e420-603b-4a8e-9920-70378b073d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-undefined-_r_1q_&quot;)</value>
      <webElementGuid>295b0806-cb55-4d94-b99b-f56573204056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-undefined-_r_1q_']</value>
      <webElementGuid>dcb5d752-6f0d-45e5-a6c8-99aa6986fa9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-accessRight']/div/div[2]/div/table/tbody/tr/td[4]/div/div/label/div/input</value>
      <webElementGuid>53ad6da4-e538-441f-9d5e-eb0f1c6abbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/label/div/input</value>
      <webElementGuid>f1a54669-5b3c-4fa3-b467-f4e1354a828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-undefined-_r_1q_' and @type = 'checkbox']</value>
      <webElementGuid>1a3f786c-2016-4ad8-aa4a-758a5ec69945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
