<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NA_checkbox-select_all-_r_1f_</name>
   <tag></tag>
   <elementGuidId>1473aeec-502a-4968-a54e-f56e2c885711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_all-_r_1f_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_all-_r_1f_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e456c69-7641-4141-a482-3759a409a246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_all-_r_1f_</value>
      <webElementGuid>56c7cac7-bff2-4dec-9ec1-145acead7461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef9c3cc6-506b-44b7-9aaa-2024da4b0454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>5ce14e9d-e8f9-4afe-86a3-d3f303b06935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_all</value>
      <webElementGuid>0b8e9179-23ef-4314-8a71-c770863e7021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3d8ab88-90fc-43dd-bf6f-5ed99fa4f729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_all-_r_1f_&quot;)</value>
      <webElementGuid>52a5325a-789c-4363-b5a2-153284e85a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_all-_r_1f_']</value>
      <webElementGuid>3bbbac05-4820-4e8b-bbd8-e811ab999087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_all']/label/div/input</value>
      <webElementGuid>e0a748a1-ef06-4d9e-bcae-8b5855656cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/div/label/div/input</value>
      <webElementGuid>998c3a32-9ad3-4adc-a4d7-765a98a295c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_all-_r_1f_' and @type = 'checkbox']</value>
      <webElementGuid>b81b20a0-7f3c-4274-b6f4-0f3a76b20e01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
