<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Intern 3_checkbox-select_row_1-_r_1d_</name>
   <tag></tag>
   <elementGuidId>0fef6e49-3be6-45fc-aa26-dd502adf863f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_1-_r_1d_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_1-_r_1d_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f096190-ad94-4b0a-bec0-30d1f62861cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_1-_r_1d_</value>
      <webElementGuid>6f184120-a293-4755-a3b3-5ce865441a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>906baa53-0bf2-40a5-a892-8aad46e88dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>1b4ca049-24cc-47dd-babc-dcaca7f4fcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_1</value>
      <webElementGuid>3fa9636e-620b-4939-9c1c-90d2a4545f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ed34ba6b-5681-4510-a95d-e2fd7451eff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_1-_r_1d_&quot;)</value>
      <webElementGuid>4873c72b-7a69-4265-9ded-dc9b93febdbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_1-_r_1d_']</value>
      <webElementGuid>7107636b-c44d-4598-836b-b421447f3947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_1']/label/div/input</value>
      <webElementGuid>da62100b-2f81-452e-b8e8-4c148d89a217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/label/div/input</value>
      <webElementGuid>0f47699f-b374-4816-a8fe-37abea1c9c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_1-_r_1d_' and @type = 'checkbox']</value>
      <webElementGuid>c0064044-876e-4f76-9840-c7af2bea2d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
