<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AccessList_checkbox-select_row_6-_r_17_</name>
   <tag></tag>
   <elementGuidId>c9ff1347-5bef-4c77-b9e6-bad649f405f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_6-_r_17_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_6-_r_17_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f4f3b45-a82e-4c16-ad2e-ce88f582e740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_6-_r_17_</value>
      <webElementGuid>a479ee5a-c97e-47f8-815a-4e2df3f95ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>34d6f408-fc86-4cc9-8767-bdeb5b599187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>ed315a8c-de35-4a44-b6d2-021911ce3eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_6</value>
      <webElementGuid>78c91ef1-39e4-41ea-844e-a1120b6f451f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3554948b-f503-44c7-bd51-04ec04c882ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_6-_r_17_&quot;)</value>
      <webElementGuid>78aa52c6-5d19-42a6-8992-20c947fae186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_6-_r_17_']</value>
      <webElementGuid>bcf3dea5-a1d7-4881-912f-ec4b0fd149ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_6']/label/div/input</value>
      <webElementGuid>a90d3e09-9f02-43fc-9216-bd8b291ac122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div/div/label/div/input</value>
      <webElementGuid>09fee944-28f1-456e-8393-60ba98b0b8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_6-_r_17_' and @type = 'checkbox']</value>
      <webElementGuid>a7ea7026-9d7a-40ec-ae1e-e8de985999d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
