<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Master Plants_checkbox-undefined-_r_1s_</name>
   <tag></tag>
   <elementGuidId>b9d7259c-3471-4bcb-a6c4-9240aa088ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-undefined-_r_1s_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-undefined-_r_1s_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49e91316-e76a-4b26-9860-5aa718fab616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-undefined-_r_1s_</value>
      <webElementGuid>a3e9e907-77b1-4502-84eb-d9ef861e7b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd165c34-6e38-41d5-bf22-dd8b568b8351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>49043e22-29f8-4451-92a6-e7f485a50a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0061aaa1-df59-42c3-97d7-0900b0028f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-undefined-_r_1s_&quot;)</value>
      <webElementGuid>0f99f931-e73b-432d-b641-48d7dd71caeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-undefined-_r_1s_']</value>
      <webElementGuid>eee79439-30c8-4803-97e5-51af26bbb74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-accessRight']/div/div[2]/div/table/tbody/tr/td[6]/div/div/label/div/input</value>
      <webElementGuid>2a33be6a-0876-4c7f-8605-ddb6ef268106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/label/div/input</value>
      <webElementGuid>861c5e12-e418-4470-b317-c75fa5d72b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-undefined-_r_1s_' and @type = 'checkbox']</value>
      <webElementGuid>d7cf2c65-f620-417f-8801-daf3a5de0d15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
