<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Master Business Partners_checkbox-und_65525a</name>
   <tag></tag>
   <elementGuidId>546ed249-6e57-42ae-98d7-f4a401269867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-undefined-_r_26_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-undefined-_r_26_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>692ae9b0-7075-44d8-9cf9-82b57badb08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-undefined-_r_26_</value>
      <webElementGuid>0a885164-5e74-4449-9461-e816b169199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02547864-417d-442d-9a39-b8692859f738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>d24dce04-8bef-4bcc-9ebb-71b6e299ea9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e9b2e9bd-a9bf-4c2f-a5ef-4dc8cb9c0ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-undefined-_r_26_&quot;)</value>
      <webElementGuid>959b3a41-a220-4ac7-823c-ad1b7f2d23cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-undefined-_r_26_']</value>
      <webElementGuid>593aebae-d3b9-48ef-b328-f3df55a10ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-accessRight']/div/div[2]/div/table/tbody/tr[2]/td[8]/div/div/label/div/input</value>
      <webElementGuid>128db00a-b91c-4db5-9765-6c62719eccf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/div/div/label/div/input</value>
      <webElementGuid>00b360c3-90be-4651-af63-1fb011db7ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-undefined-_r_26_' and @type = 'checkbox']</value>
      <webElementGuid>77d34af7-c386-4602-9f08-7f7d5a4e9d76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
