<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Intern_checkbox-select_row_2-_r_1e_</name>
   <tag></tag>
   <elementGuidId>d3202cd3-ad55-4c32-b3fb-f1f89a3282ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-select_row_2-_r_1e_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-select_row_2-_r_1e_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d5dffd9-57d8-443c-900a-f9eba8fd32c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-select_row_2-_r_1e_</value>
      <webElementGuid>a269a813-f4cc-4e3f-9a63-96ef6504c817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77804c1a-62bb-4567-8ee7-92a26484b8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute opacity-0 w-5 h-5</value>
      <webElementGuid>48fb8168-8619-4a3d-845e-a70a9907a5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select_row_2</value>
      <webElementGuid>bfaaffd8-a0af-4708-ae12-43a872f69d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f790e56d-734e-4e02-bd85-e59961c4436f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-select_row_2-_r_1e_&quot;)</value>
      <webElementGuid>5d50f89a-c7b3-4fc2-8df7-7dddc62d4ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-select_row_2-_r_1e_']</value>
      <webElementGuid>2d29059a-67f7-47cf-af0f-01c4838b02f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select_row_2']/label/div/input</value>
      <webElementGuid>668845b6-24c6-40c4-adc6-e8b8bbc4cb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/label/div/input</value>
      <webElementGuid>e498baba-c52d-4096-a24d-ae7c3485154d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-select_row_2-_r_1e_' and @type = 'checkbox']</value>
      <webElementGuid>a59618dc-f228-4164-8fc3-8cbe50e6102e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
