<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tes</name>
   <tag></tag>
   <elementGuidId>07b98f22-57f8-46e4-ae92-032917dd2158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-_r_v_-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-_r_v_-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7f88d230-0349-440d-8d8a-3d06c55973dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-_r_v_-input</value>
      <webElementGuid>f5e4ee9d-f99b-43ad-b30e-993e3833e03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write notes or additional information about this group here...</value>
      <webElementGuid>22ab0b5a-b39a-4a08-83e8-157fb9595162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f62cc9c3-7bd0-401e-b813-6fb2fb655f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full min-w-0 outline-none resize-none bg-transparent text-neutral-90 dark:text-neutral-90-dark placeholder:text-neutral-50 dark:placeholder:text-neutral-50-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>f782e251-ba9c-4d84-a3d8-75c3e0a91266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tes</value>
      <webElementGuid>6e4c6d74-31a9-49de-bf2f-0529e0744ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-_r_v_-input&quot;)</value>
      <webElementGuid>3015537f-3f04-4482-adc3-291369de4bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-_r_v_-input']</value>
      <webElementGuid>116f521a-11a3-4130-8769-2411da5644f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textarea-_r_v_']/div/textarea</value>
      <webElementGuid>c02b6f39-036d-49f0-96cb-749df82f1c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::textarea[1]</value>
      <webElementGuid>6cd8ce69-62df-4446-b518-f03e5d95ebc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record Rules'])[1]/following::textarea[1]</value>
      <webElementGuid>30998c1e-1e96-4df7-b0af-a98fe9547e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tes']/parent::*</value>
      <webElementGuid>c2b630dc-a343-416c-bd4e-56a48ed08680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b588420b-42e9-4bde-a802-d18ead731007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-_r_v_-input' and @placeholder = 'Write notes or additional information about this group here...' and (text() = 'Tes' or . = 'Tes')]</value>
      <webElementGuid>eb362780-125c-40dd-80d1-e9d2eb11e3b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
