<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_C</name>
   <tag></tag>
   <elementGuidId>2599cf68-e26e-4f1a-b045-44a294c526d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-_r_v_-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-_r_v_-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9e319578-bacd-44c9-841f-620d8463b64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-_r_v_-input</value>
      <webElementGuid>b834f8c4-35fd-417d-ac22-d56ba805daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write notes or additional information about this group here...</value>
      <webElementGuid>319ef62d-eaa3-4678-9222-ce4bde99a484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5e990618-6e59-4d4d-b034-0d333a7d336e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full min-w-0 outline-none resize-none bg-transparent text-neutral-90 dark:text-neutral-90-dark placeholder:text-neutral-50 dark:placeholder:text-neutral-50-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>64684cf6-a089-4d2d-948d-bbece781181b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>5a5a64b8-7df1-4e13-bd6e-d3d58a01cbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-_r_v_-input&quot;)</value>
      <webElementGuid>c17c96b7-ad7c-47f4-a088-bfda683add8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-_r_v_-input']</value>
      <webElementGuid>13ce8b96-214a-4eb0-9fc1-02011d520415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textarea-_r_v_']/div/textarea</value>
      <webElementGuid>5ee96085-4f77-4046-b24f-3249eb901f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::textarea[1]</value>
      <webElementGuid>7cf07dcc-f7ad-4b52-9f9c-63aa81bcb305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record Rules'])[1]/following::textarea[1]</value>
      <webElementGuid>afbcaab8-7d87-43fc-a088-53721ebebeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='C']/parent::*</value>
      <webElementGuid>204fd115-4533-42a0-b534-99abcb52c397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1eec084a-87aa-4da6-a0af-072875df7de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-_r_v_-input' and @placeholder = 'Write notes or additional information about this group here...' and (text() = 'C' or . = 'C')]</value>
      <webElementGuid>c016a769-761e-4ae9-a6f9-81a2a7db0db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
