<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Create and</name>
   <tag></tag>
   <elementGuidId>5bbea196-72b0-44cd-bfe9-5d79c2dd6c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-_r_v_-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-_r_v_-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fe036f23-20e7-4ab5-8522-8e0e53a0ab96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-_r_v_-input</value>
      <webElementGuid>d67cdd77-ede2-430c-b648-02627b14085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write notes or additional information about this group here...</value>
      <webElementGuid>d5d32376-1eb7-487b-8ea6-c39ba6b097f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>005e2c97-2542-481f-b81c-bec2ebf86862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full min-w-0 outline-none resize-none bg-transparent text-neutral-90 dark:text-neutral-90-dark placeholder:text-neutral-50 dark:placeholder:text-neutral-50-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>142c3e6a-ee63-458c-960e-98b67031face</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create and</value>
      <webElementGuid>31f31c42-b6c0-469f-9067-ca0c28912607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-_r_v_-input&quot;)</value>
      <webElementGuid>e68e4930-f78f-4b62-b18a-eb617acb9da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-_r_v_-input']</value>
      <webElementGuid>00125d91-e4df-46c4-ab4f-6ac0e7de8cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textarea-_r_v_']/div/textarea</value>
      <webElementGuid>d67fa949-a52e-415d-bba3-7bcfe2359404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::textarea[1]</value>
      <webElementGuid>c320b864-ac2e-4fae-9997-56a59ca2d2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record Rules'])[1]/following::textarea[1]</value>
      <webElementGuid>59a72dcd-5762-403b-b4a5-b8ff65f63226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create and']/parent::*</value>
      <webElementGuid>494721db-3356-4924-9533-134bf1743013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4294af82-7f05-4a93-8f89-16ccbed160ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-_r_v_-input' and @placeholder = 'Write notes or additional information about this group here...' and (text() = 'Create and' or . = 'Create and')]</value>
      <webElementGuid>86553eb8-0d8c-491d-b781-0e443eed657c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
