<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Create and Add Notes (Te</name>
   <tag></tag>
   <elementGuidId>3397421d-116b-4741-b0a8-9503b5e29a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-_r_v_-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-_r_v_-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3990825e-2f44-436a-ad0d-b852e3248f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-_r_v_-input</value>
      <webElementGuid>471192ac-2411-4497-93b9-b3d280a13705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write notes or additional information about this group here...</value>
      <webElementGuid>7880bd13-009c-4885-aab2-906d62deea40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>878fdbab-a032-43ce-9093-0a875c8dc077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full min-w-0 outline-none resize-none bg-transparent text-neutral-90 dark:text-neutral-90-dark placeholder:text-neutral-50 dark:placeholder:text-neutral-50-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>664f7687-6180-4472-83c2-1443134f0cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create and Add Notes (Te</value>
      <webElementGuid>cc9f577a-20cc-4b54-8a89-3fed4bd86796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-_r_v_-input&quot;)</value>
      <webElementGuid>e4b03d4f-6dee-4ab7-b5a8-3f484bc5d4a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-_r_v_-input']</value>
      <webElementGuid>e8733d5e-1a45-4492-90f2-49e4668ec1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textarea-_r_v_']/div/textarea</value>
      <webElementGuid>4581c9c2-439d-49f9-af47-97453302fb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::textarea[1]</value>
      <webElementGuid>83c99494-b1f7-4781-b332-f5574e2fa857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record Rules'])[1]/following::textarea[1]</value>
      <webElementGuid>e354c64a-6d49-4850-9dd6-9395f1f4d55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create and Add Notes (Te']/parent::*</value>
      <webElementGuid>ff7b4ba6-a8db-4b3d-b214-5f551f5b8456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d116d7a1-b475-4ad0-b063-92d7edc24883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-_r_v_-input' and @placeholder = 'Write notes or additional information about this group here...' and (text() = 'Create and Add Notes (Te' or . = 'Create and Add Notes (Te')]</value>
      <webElementGuid>2414782e-375d-413c-aff7-b8e23197d33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
