<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_groups_page_master_groups</name>
   <tag></tag>
   <elementGuidId>bd8f258f-fce5-444d-aec9-715da9a3543e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c80bd294-2220-4928-bb03-29b493723e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-24px leading-[28px] font-bold -tracking-[2%]</value>
      <webElementGuid>7850831f-ef9f-403a-b41a-96dc3628552a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Groups</value>
      <webElementGuid>f59d84d3-1c26-40e7-a7bf-4ea1cee07299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;relative min-h-screen min-w-screen-lg bg-neutral-15 pt-20&quot;]/div[2]/div[@class=&quot;sticky top-20 z-10 px-6 py-4 bg-neutral-15&quot;]/div[@class=&quot;flex items-center justify-between py&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/h4[@class=&quot;text-24px leading-[28px] font-bold -tracking-[2%]&quot;]</value>
      <webElementGuid>7ff6c6d1-5c2e-453b-a3d6-cab0afa4e75e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/h4</value>
      <webElementGuid>3bc7cdcf-6170-46f0-9aaa-0607f473be83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utility'])[1]/preceding::h4[1]</value>
      <webElementGuid>67707816-2682-4258-b844-a6106af3e5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::h4[1]</value>
      <webElementGuid>bd07ccc9-c5b6-41cd-9235-a15ac7d1ea5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Groups']/parent::*</value>
      <webElementGuid>7f38d95f-9ae9-4969-8e5b-7f15496bd539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>c170f603-7939-4d01-a0f2-0139cc715601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Groups' or . = 'Groups')]</value>
      <webElementGuid>26c4d8de-62dd-4293-bb2f-de42e376acfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
