<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_group_status</name>
   <tag></tag>
   <elementGuidId>607e55d0-fe1c-4204-aa42-9141eeac4de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1905bc13-8f34-4399-84ef-9ac40af7e3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e9607c3-1080-4eca-92b6-34761431b6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab4866a9-8915-4f88-8048-68995587a6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-full transition-colors relative focus:ring-3 ring-primary-focus dark:ring-primary-focus-dark w-7 h-4 bg-neutral-40 dark:bg-neutral-40-dark</value>
      <webElementGuid>b4f96976-6fa8-4274-88ff-2d95de9a82c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;relative min-h-screen min-w-screen-lg bg-neutral-15 pt-20&quot;]/div[2]/div[@class=&quot;px-6 py-4 flex flex-col gap-4&quot;]/div[@class=&quot;bg-neutral-10 rounded-2xl p-4 border border-neutral-30&quot;]/form[@class=&quot;w-full max-w-screen-sm flex flex-col gap-3&quot;]/div[@class=&quot;flex gap-3 min-h-8 items-start&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative flex text-neutral-90 dark:text-neutral-90-dark flex-col gap-0.5&quot;]/div[@class=&quot;w-fit flex items-center gap-2.5 rounded-md py-1.5&quot;]/div[1]/div[@class=&quot;rounded-full transition-colors relative focus:ring-3 ring-primary-focus dark:ring-primary-focus-dark w-7 h-4 bg-neutral-40 dark:bg-neutral-40-dark&quot;]</value>
      <webElementGuid>81f7890f-e62e-4bbb-9c6d-c8794b27df4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/div/div/div</value>
      <webElementGuid>f32767a9-44a8-4002-91ed-97142c39f36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/following::div[7]</value>
      <webElementGuid>4c748dc4-85c2-496f-b27a-da3908590ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[20]</value>
      <webElementGuid>d394dc7e-57f3-42f2-aff8-f6e0a3ca2fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[2]/preceding::div[2]</value>
      <webElementGuid>c4e220ae-4ff3-477b-940e-fe0247e2094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::div[4]</value>
      <webElementGuid>c3c9db00-070f-4ced-b9e3-34c97c9cca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div</value>
      <webElementGuid>1dd134fd-ac4a-41a9-8260-9ca6664bee4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
