<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_field_Name Business Partner</name>
   <tag></tag>
   <elementGuidId>d4f7eead-6843-46c4-bfe7-871a2b27facb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textfield-name-_r_j_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield-name-_r_j_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a28ed42c-ffce-4f93-a8be-6aa0ad92b4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf090903-d768-4611-a29a-4dcae00e9550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield-name</value>
      <webElementGuid>f6173782-c1bf-48b1-942b-a6058b2fb04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark text-neutral-90 dark:text-neutral-90-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>4813e735-0c36-4daa-91fc-ec0c269304af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>8b486beb-c78d-421d-9cbd-36a981ee6217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textfield-name-_r_j_&quot;)</value>
      <webElementGuid>280432da-631d-40fe-87bb-570c3a400245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield-name-_r_j_']</value>
      <webElementGuid>cd29d44b-04fd-415a-8782-56013bb9351d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[2]/div[2]/div/input</value>
      <webElementGuid>fbb3522b-2ebb-4d80-9b6b-d5d8f7bba4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>20125793-e6ac-4be8-9118-6700abe0b81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textfield-name-_r_j_' and @name = 'name']</value>
      <webElementGuid>87ada6a7-0295-4731-a5d8-791b27313e02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
