<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_field_Code Business Partner</name>
   <tag></tag>
   <elementGuidId>844372ed-6fac-4a0a-ac05-66687ca7a2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textfield-code-_r_i_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield-code-_r_i_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad8619d6-ee14-4a3a-9f23-3a9e241a0b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f2d6d0e3-56f3-45d1-bd2e-d7a39c56f64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield-code</value>
      <webElementGuid>2b69be19-2487-4188-8d9f-c655a584520b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark text-neutral-90 dark:text-neutral-90-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>6dc4e805-d643-4599-9e44-65c3ccd8b434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>c5727823-fde4-4281-a2c2-443b83632b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textfield-code-_r_i_&quot;)</value>
      <webElementGuid>e53cef23-1b84-4716-a709-7c092127583b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield-code-_r_i_']</value>
      <webElementGuid>518bd3d7-f431-48ae-be18-84edbe904be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div/div[2]/div/input</value>
      <webElementGuid>a9fb1c18-aa0f-446d-9aec-ba24251a174f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8a633d8f-cfee-4073-b6a0-85415c01d7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textfield-code-_r_i_' and @name = 'code']</value>
      <webElementGuid>dbb2c682-deb3-4286-9b6d-cf396af070a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
