<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_fiels_Remarks Business Partner</name>
   <tag></tag>
   <elementGuidId>2fac48dd-a047-47e9-a654-1f94d8e46fe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-remarks-_r_l_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-remarks-_r_l_']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@id, 'textarea-remarks') and @name = 'remarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a35a4987-5854-48f1-b70c-440629c71952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>917e72b5-bc45-445d-a3e9-af9187e49f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-remarks</value>
      <webElementGuid>39e4e0bb-a327-4de8-90d3-398b5851ee07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>8ed60830-b55d-44ff-b330-4cb14c22f6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none resize-none bg-neutral-10 dark:bg-neutral-10-dark disabled:bg-neutral-20 dark:disabled:bg-neutral-30-dark disabled:cursor-not-allowed text-14px py-0.5</value>
      <webElementGuid>bc97e9a9-cb6a-4c0b-abb6-95ced1c83ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>51c4ffdd-286c-4c26-8f53-9af3c9fff519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-remarks-_r_l_&quot;)</value>
      <webElementGuid>eec5d1ba-111c-43f2-bb95-e677ff555f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-remarks-_r_l_']</value>
      <webElementGuid>582d5497-9eac-4efb-8c9d-f78dcea638fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/textarea</value>
      <webElementGuid>19de7213-08fb-4989-9036-b50c470f5127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>69066ff3-caba-4b3d-a21b-a3803fc5502e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-remarks-_r_l_' and @name = 'remarks']</value>
      <webElementGuid>885171c4-574c-40e8-8ea7-9d78f21f0a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
