<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Password_password-show-password</name>
   <tag></tag>
   <elementGuidId>d1b20d15-3385-47e2-8c76-ed697254f9f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-show-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='password-show-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07fbe831-b300-418d-bea3-e25b102335cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf-v5-c-button pf-m-control</value>
      <webElementGuid>c85231ee-21db-44b6-a1a1-59898bcbedb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0920f72a-b958-426a-87e6-f4a5a16086a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show password</value>
      <webElementGuid>bf379b4c-77fb-478a-a9f6-4d075e0314f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e9d8aca9-c980-4c3e-8112-2f34c034eb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-show</name>
      <type>Main</type>
      <value>fa-eye fas</value>
      <webElementGuid>ac33ea30-1246-402d-bef2-589a77d7494b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-hide</name>
      <type>Main</type>
      <value>fa-eye-slash fas</value>
      <webElementGuid>718eb284-63c5-49b1-9f33-33441575ef12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-show</name>
      <type>Main</type>
      <value>Show password</value>
      <webElementGuid>5a8e9e26-ad07-4cb9-9c1f-ace0e386445e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-hide</name>
      <type>Main</type>
      <value>Hide password</value>
      <webElementGuid>3a8dbe7e-e18a-4c7b-a0fa-ada1ea4c4e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-show-password</value>
      <webElementGuid>b1da23de-0549-4b8a-8b26-73b4384994bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-show-password&quot;)</value>
      <webElementGuid>ebdfb4bc-aca3-49f0-8501-507d8786809c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='password-show-password']</value>
      <webElementGuid>e79b92f1-7091-4547-b60d-4615981ee807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>9cc4c58b-10e3-40f6-9bec-7f7bb72054c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>85be74a9-86e4-4d84-9534-79604039010d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username or email'])[1]/following::button[1]</value>
      <webElementGuid>473451f3-45df-430b-8040-da813c320c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>37ca0e6d-db97-46f6-8b6f-16be467dc46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::button[1]</value>
      <webElementGuid>4e2e8ac2-261a-4de7-a7c5-51ec62448f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d2585716-5fdb-4240-b769-2a5508c3f010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'password-show-password']</value>
      <webElementGuid>f177867c-45de-47e9-929f-5e5307fa55bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
